# Generated by Django 4.2.7 on 2023-11-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0)),
                ('categorie_socio_professionnelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_panier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_export.client')),
            ],
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identifiant_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_export.clientcollecte')),
            ],
        ),
    ]
